Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    [Table("pizzas")]
    public class Pizza
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Column("name")]
        public string Name { get; private set; }

        [Column("ingredients", TypeName = "text")]
        public string Ingredients { get; private set; }

        [Column("photo")]
        public string Photo { get; private set; }

        [Required]
        [Column("price", TypeName ="decimal(5,2)")]
        public decimal Price { get; private set; }

        public Pizza(string name, string ingredients, string photo, decimal price)
        {
            this.Name = name;
            this.Ingredients = ingredients;
            this.Photo = photo;
            this.Price = price;
        }

    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Home";
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        // GET: HomeController1
        public ActionResult Menu()
        {
            List<Pizza> pizze;

            using (PizzaContext db = new PizzaContext())
            {
                pizze = db.Pizzas.ToList();
            }

            ViewData["Title"] = "Menu";

            return View(pizze);
        }

        // GET: HomeController1/Details/5
        public ActionResult Details(int id)
        {

            Pizza pizzaCurrent;

            using (PizzaContext db = new PizzaContext())
            {
                pizzaCurrent = db.Pizzas.Where(p => p.Id == id).FirstOrDefault();
            }

            if(pizzaCurrent == null)
            {
                ViewData["Title"] = "Error404";
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return View("Error404");
            }
            else
            {
                ViewData["Title"] = pizzaCurrent.Name;
                return View(pizzaCurrent);
            }

        }

        // GET: HomeController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController1/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Home/Index.cshtml
<main class="pizza-background welcome-wrapper pizza-background d-flex flex-column align-items-center h-100 w-100 justify-content-center">
    <h1 class="title">PIZZABOOL</h1>
    <h3 class="menu-title pt-3"><a asp-controller="Pizza" asp-action="Menu">Menù</a></h3>
</main>

Views/Pizza/Details.cshtml
@model Pizza
@{
    string[] ingredienti = Model.Ingredients.Split(",");
}

<main class="patter-background p-3 pt-5 pb-5 welcome-wrapper d-flex flex-column align-items-center h-100 w-100 justify-content-center">

    <h4 class="fw-bold mb-3"><a asp-controller="Pizza" asp-action="Menu">Torna al Menù</a></h4>

    <section class="pizza-detail container col-12 col-lg-9 col-xl-8 d-flex-column d-md-flex p-2 p-sm-3 p-md-5">

        <div class="col-12 col-md-6 d-flex justify-content-center position-relative">

            <div class="price-details position-absolute d-flex justify-content-center align-items-center p-1">
                <h5 class="m-0 fw-bold">@Model.Price €</h5>
            </div>

            <img src="/img/@Model.Photo" alt="foto-pizza"/>
            
        </div>

        <div class="col-12 col-md-6">

            <h2 class="text-center text-name" >@Model.Name</h2>

            <div class="ingredients-wrapper pt-3 p-4 p-sm-5">
                <p  class="mb-2 fw-bold">Ingredienti:</p>

                <ul>
                    @foreach(string  ingrediente in ingredienti)
                    {
                        <li class="ms-4">@ingrediente</li>
                    }

                </ul>
            </div>
        </div>

    </section>

</main>

Views/Pizza/Menu.cshtml
@model List<Pizza>

<main class="patter-background p-3 welcome-wrapper d-flex flex-column align-items-center h-100 w-100 justify-content-center">

    @if(Model.Count() == 0)
    {
        <div class="p-3 text-center">
            <h1>Attualmente non è presente nessuna pizza nella nostra applicazione!</h1>
        </div>
    }

    else
    {
        <div class="container-fluid container-lg d-flex justify-content-center flex-wrap gap-4 p-3">

            <ul>
                @foreach(Pizza pizza in Model){
                    <a asp-area="" asp-controller="Pizza" asp-action="Details" asp-route-id="@pizza.Id">

                        <li class="pizza-wrapper d-flex flex-column align-items-center p-4 position-relative mb-3">

                        @*Immagine e prezzo*@
                        <div class="img-wrapper mb-3">
                            <img src="/img/@pizza.Photo">

                            @*prezzo*@
                            <div class="price-wrap d-flex justify-content-end">
                            <p class="price-pizza m-0 pe-2">@pizza.Price €</p>
                            </div>
                        </div>

                        @*Nome pizza*@
                        <h3 class="text-name">@pizza.Name</h3>

                    </li>

                    </a>                    
                }
            </ul>              

        </div>
    }

    
</main>

Views/Shared/Error404.cshtml
<main class="patter-background p-3 welcome-wrapper d-flex flex-column align-items-center h-100 w-100 justify-content-center">

    <div class="p-3 text-center d-flex flex-column align-items-center">
        <figure class="w-50">
            <img src="~/img/sad_pizza.png"/>
        </figure>
        <h1>PAGINA NON TROVATA</h1>
    </div>
    
</main>

Views/Shared/_Footer.cshtml
<div class="d-flex justify-content-between">
    <p class="m-1">&copy; 2022 - PizzaBool</p>
    <p  class="m-1">by <a href="https://www.flowcode.com/page/ilguarnieri" target="_blank">Angelo Guarnieri</a></p>
</div>

Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
    <div class="container-fluid container-lg ps-xxl-5 pe-xxl-5">
        <a class="navbar-brand" href="#">
            <img src="/img/icon.png" alt="logo" width="30" height="24">
        </a>
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaBool</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex">
            <ul class="navbar-nav flex-grow-1  justify-content-end">
                <li class="nav-item">
                    <a id="home" class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" >Home</a>
                </li>
                <li class="nav-item">
                    <a id="menu" class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Menu">Menù</a>
                </li>
            </ul>
        </div>
    </div>
    
    <script>
        const ind = "@ViewData["Title"].ToString().ToLower()";
        const item = document.getElementById(ind);
        item.classList.add("active-item");
    </script>
</nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaBool</title>
    <link rel="icon" href="/img/icon.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>

<body class="d-flex flex-column">

    <header>
        @Html.Partial("_Header")
    </header>

    <div class="flex-grow-1">
        @RenderBody()
    </div>

    <footer class="footer text-muted container-fluid container-lg ps-xxl-5 pe-xxl-5">
        @Html.Partial("_Footer")
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>